# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 686c6b18900ef6df312ef73814726b3738f83b23947fff08270880627c65a1a7384365c977e9e9ef7b58511c55c80cce0d4fbc0665afb792a855ea7057f30928

test:
  secret_key_base: 6bdfead33f92a74e8c1f42755068c4c77e83693004bc682b723a31ce3d431538df660b74de19a063c32494b54681971262790eb9017bc1bd6be7b09488293b1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
